### ISSUE TITLE
stopValue and set() using integers?

### ISSUE THREAD

**Issue by kpowick** [crossproduct/ProgressCircle#3]
The _Option_ `stopValue` and _Function_ `set()` indicate an _integer_ value between 0 and 1.  Aren't these really decimal (float) values between 0 and 1? e.g. 0.25, 0.50, 0.75, etc.

It's easy enough to figure out, but slightly confusing, to me anyway. I think that either the documentation should be clarified, or the code changed to actually use integers between 0 and 100.

**Comment by crossproduct** [comment]
You're absolutely correct, and thanks for the feedback! Let me fix that ASAP!
