### ISSUE TITLE
[Enhancement]: Add animation

### ISSUE THREAD

**Issue by arkany** [crossproduct/ProgressCircle#4]
If you think it wise and useful...

Allow the progress circle to animate from one value to another, either forwards or backwards(ie- 50% to 20%).

**Comment by crossproduct** [comment]
Great suggestion! I think this should be broken into 2 distinct enhancements. One to allow animations to go in reverse and another to address the relative 'animateTo()' functionality. 

https://github.com/crossproduct/ProgressCircle/issues/5
https://github.com/crossproduct/ProgressCircle/issues/6
